import Head from 'next/head'
import Header from '../components/Header'
import { getSession } from "next-auth/react"
import Login from '../components/Login'
import SideBar from '../components/sideBar'
import Feed from '../components/Feed';



export default function Home({ session }) {
  if(!session) return <Login/>
  return (
    <div className="h-screen overflow-hidden bg-gray-100">
      <Head>
        <title>Fakebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    {/* header */}
      <Header/>

      <main className="flex">
        <SideBar/>
        <Feed/>
      </main>
     
    </div>
  )
}


export async function getServerSideProps(context) {
  // get user 
  const session = await getSession(context);

  return {
    props: {
      session
    }
  }
}
